import os
import gc
import base64
import pickle
import datetime
import torch
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from bs4 import BeautifulSoup
import re

from google.oauth2.credentials import Credentials
from google.auth.transport.requests import Request
from googleapiclient.discovery import build
from transformers import AutoTokenizer, AutoModelForCausalLM

# ── Config ────────────────────────────────────────
SCOPES       = ['https://mail.google.com/']
TARGET_DOMAINS = ['go.umterps.com', 'umd.edu']
FROM_EMAIL   = os.environ['FROM_EMAIL']
TO_EMAIL     = os.environ['TO_EMAIL']
MAX_EMAILS   = 20
# ─────────────────────────────────────────────────


def get_gmail_service():
    """Load credentials from environment variable"""
    token_data = base64.b64decode(os.environ['GMAIL_TOKEN']).decode()
    creds = Credentials.from_authorized_user_info(
        __import__('json').loads(token_data), SCOPES
    )
    if creds.expired and creds.refresh_token:
        creds.refresh(Request())
    return build('gmail', 'v1', credentials=creds)


def extract_body(payload):
    def find_plain_text(part):
        if part.get('mimeType') == 'text/plain':
            data = part.get('body', {}).get('data', '')
            if data:
                return base64.urlsafe_b64decode(data).decode('utf-8', errors='ignore')
        for subpart in part.get('parts', []):
            result = find_plain_text(subpart)
            if result:
                return result
        return ''

    body = find_plain_text(payload)
    body = re.sub(r'http\S+', '[link]', body)
    body = re.sub(r'<[^>]+>', '', body)
    body = re.sub(r'\s+', ' ', body)
    body = re.sub(r'(\[link\]\s*)+', '[link] ', body)
    return body.strip()


def fetch_emails_by_domain(service, domain, max_results):
    results = service.users().messages().list(
        userId='me', q=f'from:@{domain}', maxResults=max_results
    ).execute()
    messages = results.get('messages', [])

    emails = []
    for msg in messages:
        detail = service.users().messages().get(
            userId='me', id=msg['id'], format='full'
        ).execute()
        headers = detail['payload']['headers']
        subject = next((h['value'] for h in headers if h['name'] == 'Subject'), 'No Subject')
        sender  = next((h['value'] for h in headers if h['name'] == 'From'), 'Unknown')
        body    = extract_body(detail['payload'])
        emails.append({'subject': subject, 'from': sender, 'body': body[:150]})
    return emails


def summarize(tokenizer, model, domain, emails):
    email_text = ""
    for e in emails[:8]:
        email_text += f"- From: {e['from']} | Subject: {e['subject']}\n  {e['body']}\n\n"

    prompt = f"""<|system|>
You are an executive assistant.</s>
<|user|>
Summarize these emails from {domain}. Include overall theme, key action items, and urgent matters.

{email_text[:1200]}</s>
<|assistant|>
Summary:"""

    gc.collect()
    torch.cuda.empty_cache() if torch.cuda.is_available() else None

    inputs = tokenizer(
        prompt, return_tensors="pt",
        truncation=True, max_length=1600
    ).to(model.device)

    with torch.no_grad():
        outputs = model.generate(
            **inputs,
            max_new_tokens=300,
            do_sample=True,
            temperature=0.7,
            top_p=0.95,
            repetition_penalty=1.3,
            no_repeat_ngram_size=3,
            pad_token_id=tokenizer.eos_token_id,
            eos_token_id=tokenizer.eos_token_id
        )

    new_tokens = outputs[0][inputs['input_ids'].shape[1]:]
    response = tokenizer.decode(new_tokens, skip_special_tokens=True).strip()

    del inputs, outputs, new_tokens
    gc.collect()

    return response if len(response) > 10 else "Summary generation failed."


def send_email(service, from_email, to_email, domain_summaries):
    msg = MIMEMultipart('alternative')
    msg['Subject'] = f"📧 Daily Email Summary - {datetime.datetime.now().strftime('%B %d, %Y')}"
    msg['From']    = from_email
    msg['To']      = to_email

    plain = f"Daily Email Summary\n{'='*40}\n"
    for domain, summary in domain_summaries.items():
        plain += f"\n{domain}\n{'-'*30}\n{summary}\n"
    plain += "\n---\nAuto-generated by Email Intelligence Bot."

    colors = ['4FC3F7', '00C896', 'FF9D45']
    sections = ""
    for i, (domain, summary) in enumerate(domain_summaries.items()):
        color = colors[i % len(colors)]
        sections += f"""
        <div style="margin-bottom:25px;border-left:4px solid #{color};padding:15px;background:#f9f9f9;border-radius:4px;">
            <h3 style="color:#{color};margin:0 0 10px 0;">📧 {domain}</h3>
            <div style="font-size:14px;line-height:1.7;color:#333;">{summary.replace(chr(10),'<br>')}</div>
        </div>"""

    html = f"""<html><body style="font-family:Arial,sans-serif;max-width:700px;margin:auto;padding:20px;">
    <div style="background:#1E2761;padding:20px;border-radius:6px;margin-bottom:25px;">
        <h2 style="color:#fff;margin:0;">📬 Daily Email Summary</h2>
        <p style="color:#CADCFC;margin:5px 0 0;">{datetime.datetime.now().strftime('%B %d, %Y %I:%M %p')} · {len(domain_summaries)} domains</p>
    </div>
    {sections}
    <p style="color:#aaa;font-size:12px;border-top:1px solid #eee;padding-top:10px;">Auto-generated by Email Intelligence Bot.</p>
</body></html>"""

    msg.attach(MIMEText(plain, 'plain'))
    msg.attach(MIMEText(html, 'html'))
    raw = base64.urlsafe_b64encode(msg.as_bytes()).decode()
    sent = service.users().messages().send(userId='me', body={'raw': raw}).execute()
    print(f"✅ Email sent! ID: {sent['id']}")


def main():
    print("Loading Gmail service...")
    service = get_gmail_service()

    print("Loading AI model...")
    model_id = "TinyLlama/TinyLlama-1.1B-Chat-v1.0"
    tokenizer = AutoTokenizer.from_pretrained(model_id)
    model = AutoModelForCausalLM.from_pretrained(
        model_id,
        torch_dtype=torch.float16 if torch.cuda.is_available() else torch.float32,
        device_map="auto"
    )

    domain_summaries = {}
    for domain in TARGET_DOMAINS:
        print(f"\n📧 Processing {domain}...")
        emails = fetch_emails_by_domain(service, domain, MAX_EMAILS)
        print(f"Found {len(emails)} emails")
        if emails:
            domain_summaries[domain] = summarize(tokenizer, model, domain, emails)
            print(f"✅ Summary done: {len(domain_summaries[domain])} chars")

    print("\nSending summary email...")
    send_email(service, FROM_EMAIL, TO_EMAIL, domain_summaries)
    print("✅ Done!")


if __name__ == "__main__":
    main()
```

---

**File 2 — `requirements.txt`:**
```
google-auth
google-auth-httplib2
google-api-python-client
transformers
torch
accelerate
beautifulsoup4
